name: QA Automation

on:
  push:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy

    steps:
      - uses: actions/checkout@v4

      - name: Setup for 23f2003092@ds.study.iitm.ac.in
        run: echo "Starting QA job"

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Script
        run: node sumTables.js
