name: QA Automation - 23f2003092@ds.study.iitm.ac.in

on:
  push:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - uses: microsoft/playwright-github-action@v1

      - run: node sumTables.js
